apiVersion: v1
kind: Secret
metadata:
  name: remotion-secrets
type: Opaque
data:
  # These values will be replaced by the deployment script
  supabase-url: ${BASE64_ENCODED_SUPABASE_URL}
  supabase-key: ${BASE64_ENCODED_SUPABASE_KEY}
